# Generated by Django 5.2.17 on 2026-08-15 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HotelOwner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=280, null=True, unique=True
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("mobile", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "cancellation_policy",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                (
                    "refund_policy",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                ("verified", models.BooleanField(default=False)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Deactivating an owner also hides all of their hotels from the public API.",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "verified"],
            },
        ),
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=280, null=True, unique=True
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("PUBLISHED", "Published")],
                        default="PUBLISHED",
                        help_text="Editorial state (draft/published) - independent of is_active.",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hotels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hotels",
                        to="django_hotels.hotelowner",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="HotelImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.URLField()),
                ("caption", models.CharField(blank=True, max_length=255, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="django_hotels.hotel",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="HotelRoomType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("base_price", models.DecimalField(decimal_places=0, max_digits=10)),
                ("max_occupancy", models.PositiveIntegerField(default=2)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_types",
                        to="django_hotels.hotel",
                    ),
                ),
            ],
            options={
                "ordering": ["base_price"],
            },
        ),
        migrations.CreateModel(
            name="HotelAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        help_text="Overrides room_type.base_price for this date when set.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("rooms_available", models.PositiveIntegerField(default=1)),
                (
                    "room_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availabilities",
                        to="django_hotels.hotelroomtype",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Hotel availabilities",
                "ordering": ["date"],
                "unique_together": {("room_type", "date")},
            },
        ),
        migrations.CreateModel(
            name="HotelBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated booking reference number",
                        max_length=16,
                        unique=True,
                    ),
                ),
                (
                    "otp",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated 4-digit code, paired with `number` as an alternative to `number` + `email` for the guest booking lookup.",
                        max_length=4,
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=30)),
                ("guests", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("WAITING_PAYMENT", "Awaiting Payment"),
                            ("CONFIRMED", "Confirmed"),
                            ("PARTIAL_PAYMENT", "Partial Payment"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "total_price",
                    models.DecimalField(decimal_places=0, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "availability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="django_hotels.hotelavailability",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this booking (null for guest bookings)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hotel_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["status"], name="django_hote_status_50c4cc_idx"
                    )
                ],
            },
        ),
    ]
