# Generated by Django 5.2.17 on 2026-08-27 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_hotels', '0003_backfill_hotel_locations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='city',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotels', to=settings.DJANGO_HOTELS_LOCATION_MODEL),
        ),
    ]
