# Generated by Django 5.2.17 on 2026-08-21 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_hotels', '0001_initial'),
        migrations.swappable_dependency(settings.DJANGO_HOTELS_LOCATION_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, null=True, unique=True)),
                ('lat', models.CharField(blank=True, max_length=20, null=True)),
                ('lng', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'ordering': ['name'],
                'swappable': 'DJANGO_HOTELS_LOCATION_MODEL',
            },
        ),
        migrations.AlterField(
            model_name='hotel',
            name='city',
            field=models.CharField(help_text='Free-text city name - superseded by `location`, kept until every row has been backfilled and this field is dropped (see P9.3/P9.6).', max_length=100),
        ),
        migrations.AddField(
            model_name='hotel',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Structured location - backfilled from `city` where it cleanly matches (see the 0003 migration); `city` stays in place until every row is backfilled.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotels', to=settings.DJANGO_HOTELS_LOCATION_MODEL),
        ),
    ]
